KERNEL_SOURCES := \
	arch/mips/backtrace/mips_stacktrace.c \
	arch/mips/cpu.c \
	arch/mips/init_hook.c \
	arch/mips/mips32r1/boot.S \
	arch/mips/mips32r1/cache.S \
	arch/mips/mips32r1/init_hook.c \
	arch/mips/mips32r1/interrupt.S \
	arch/mips/mips32r1/mips-bswap.S \
	drivers/aplatform/cjc8988-dai.c \
	drivers/aplatform/cjc8990-dai.c \
	drivers/aplatform/cs4344-dai.c \
	drivers/aplatform/i2si0_platform_reg.c \
	drivers/aplatform/i2si1_platform_reg.c \
	drivers/aplatform/i2si2_platform_reg.c \
	drivers/aplatform/i2si_platform_reg.c \
	drivers/aplatform/i2so_platform_reg.c \
	drivers/aplatform/pcmi0_platform_reg.c \
	drivers/aplatform/pcmi1_platform_reg.c \
	drivers/aplatform/pcmi2_platform_reg.c \
	drivers/aplatform/pcmi_platform_reg.c \
	drivers/aplatform/pcmo_platform_reg.c \
	drivers/aplatform/pdmi0_platform_reg.c \
	drivers/aplatform/tdmi_platform_reg.c \
	drivers/aplatform/wm8960-dai.c \
	drivers/aplatform/wm8960-for-i2si-dai.c \
	drivers/aplatform/wm8960i-dai.c \
	drivers/av/avinit.c \
	drivers/base/module.c \
	drivers/base/notify.c \
	drivers/base/sysdata.c \
	drivers/clock/hc_clk_gate.c \
	drivers/devnull/devnull.c \
	drivers/dummyuart/dummyuart.c \
	drivers/fileuart/fileuart.c \
	drivers/ge/ge.c \
	drivers/gpio/gpio.c \
	drivers/gpio/gpioirq.c \
	drivers/hwspinlock/hwspinlock.c \
	drivers/i2c/hc-i2c.c \
	drivers/input/input-mt.c \
	drivers/input/input.c \
	drivers/input/rc/hc_rc.c \
	drivers/input/rc/ir-nec-decoder.c \
	drivers/input/rc/keymaps/rc-hcdemo.c \
	drivers/input/rc/rc-ir-raw.c \
	drivers/input/rc/rc-main.c \
	drivers/kshm/kshm.c \
	drivers/lcd/display/st7789v2.c \
	drivers/lcd/backlight.c \
	drivers/lcd/lcd_main.c \
	drivers/mmz/mmz.c \
	drivers/mtd/cmd_mtd.c \
	drivers/mtd/mtd-porting.c \
	drivers/mtd/mtdcore.c \
	drivers/mtd/of_mtd.c \
	drivers/mtd/spi-nor/atmel.c \
	drivers/mtd/spi-nor/catalyst.c \
	drivers/mtd/spi-nor/core.c \
	drivers/mtd/spi-nor/eon.c \
	drivers/mtd/spi-nor/esmt.c \
	drivers/mtd/spi-nor/everspin.c \
	drivers/mtd/spi-nor/fujitsu.c \
	drivers/mtd/spi-nor/general.c \
	drivers/mtd/spi-nor/gigadevice.c \
	drivers/mtd/spi-nor/intel.c \
	drivers/mtd/spi-nor/issi.c \
	drivers/mtd/spi-nor/macronix.c \
	drivers/mtd/spi-nor/micron-st.c \
	drivers/mtd/spi-nor/sfdp.c \
	drivers/mtd/spi-nor/spansion.c \
	drivers/mtd/spi-nor/sst.c \
	drivers/mtd/spi-nor/winbond.c \
	drivers/mtd/spi-nor/xilinx.c \
	drivers/mtd/spi-nor/xmc.c \
	drivers/pinmux/pinmux.c \
	drivers/pwm/hc-pwm.c \
	drivers/saradc/hc_saradc_clk_init.c \
	drivers/spi/hc-spi.c \
	drivers/spi/spi-mem.c \
	drivers/spi/spi.c \
	drivers/uart/uart.c \
	drivers/video/fb.c \
	drivers/video/fbcmap.c \
	drivers/video/hc16xx_fb.c \
	drivers/video/hc16xx_fb_filter.c \
	freertos/event_groups.c \
	freertos/list.c \
	freertos/portable/FreeRTOS_POSIX_port.c \
	freertos/portable/GCC/MIPS32_HC16xx/port.c \
	freertos/portable/GCC/MIPS32_HC16xx/port_asm.S \
	freertos/portable/GCC/MIPS32_HC16xx/port_interrupt.c \
	freertos/portable/GCC/MIPS32_HC16xx/port_stats.c \
	freertos/portable/GCC/MIPS32_HC16xx/port_timer.c \
	freertos/queue.c \
	freertos/stream_buffer.c \
	freertos/tasks.c \
	freertos/timers.c \
	fs/mount/fs_automount.c \
	fs/partition/fs_smbr.c \
	lib/console/console.c \
	lib/crc/crc32.c \
	lib/easylogger/port/elog_port.c \
	lib/easylogger/src/elog.c \
	lib/easylogger/src/elog_async.c \
	lib/easylogger/src/elog_buf.c \
	lib/easylogger/src/elog_utils.c \
	lib/fdt/fdt.c \
	lib/fdt/fdt_api.c \
	lib/fdt/fdt_ro.c \
	lib/fdt/fdt_rw.c \
	lib/libc/_platform_time.c \
	lib/libc/abort.c \
	lib/libc/alloc.c \
	lib/libc/basename.c \
	lib/libc/callocr.c \
	lib/libc/clock_gettime.c \
	lib/libc/clock_settime.c \
	lib/libc/delay.c \
	lib/libc/environ.c \
	lib/libc/errno.c \
	lib/libc/execve.c \
	lib/libc/exit.c \
	lib/libc/fesetround.c \
	lib/libc/ffs.c \
	lib/libc/fork.c \
	lib/libc/freer.c \
	lib/libc/getchar.c \
	lib/libc/getentropy.c \
	lib/libc/getpid.c \
	lib/libc/gettimeofday.c \
	lib/libc/hostname.c \
	lib/libc/isatty.c \
	lib/libc/kill.c \
	lib/libc/mallocr.c \
	lib/libc/msleep.c \
	lib/libc/putchar.c \
	lib/libc/reallocr.c \
	lib/libc/settimeofday.c \
	lib/libc/sleep.c \
	lib/libc/times.c \
	lib/libc/usleep.c \
	lib/libc/wait.c \
	lib/lzma/LzmaDec.c \
	lib/lzma/LzmaUtils.c \
	lib/zlib/gunzip.c \
	sched/completion.c \
	sound/audsink_conf.c \
	sound/copyframe_16bit.c \
	sound/snd_core.c \
	third_party/FatFs/source/diskio.c \
	third_party/FatFs/source/ff.c \
	third_party/FatFs/source/ffsystem.c \
	third_party/FatFs/source/ffunicode.c \
	third_party/FatFs/source/fs_fat32.c \
	third_party/linux/init.c \
	third_party/nuttx/drivers/bch/bchdev_driver.c \
	third_party/nuttx/drivers/bch/bchdev_register.c \
	third_party/nuttx/drivers/bch/bchdev_unregister.c \
	third_party/nuttx/drivers/bch/bchlib_cache.c \
	third_party/nuttx/drivers/bch/bchlib_read.c \
	third_party/nuttx/drivers/bch/bchlib_sem.c \
	third_party/nuttx/drivers/bch/bchlib_setup.c \
	third_party/nuttx/drivers/bch/bchlib_teardown.c \
	third_party/nuttx/drivers/bch/bchlib_write.c \
	third_party/nuttx/drivers/i2c/i2c_driver.c \
	third_party/nuttx/drivers/i2c/i2c_read.c \
	third_party/nuttx/drivers/i2c/i2c_write.c \
	third_party/nuttx/drivers/i2c/i2c_writeread.c \
	third_party/nuttx/drivers/mkrd.c \
	third_party/nuttx/drivers/mtd/ftl.c \
	third_party/nuttx/drivers/mtd/mtd_partition.c \
	third_party/nuttx/drivers/pwm/pwm.c \
	third_party/nuttx/drivers/ramdisk.c \
	third_party/nuttx/fs/dirent/fs_closedir.c \
	third_party/nuttx/fs/dirent/fs_opendir.c \
	third_party/nuttx/fs/dirent/fs_readdir.c \
	third_party/nuttx/fs/dirent/fs_rewinddir.c \
	third_party/nuttx/fs/dirent/fs_seekdir.c \
	third_party/nuttx/fs/dirent/fs_telldir.c \
	third_party/nuttx/fs/driver/fs_blockproxy.c \
	third_party/nuttx/fs/driver/fs_closeblockdriver.c \
	third_party/nuttx/fs/driver/fs_findblockdriver.c \
	third_party/nuttx/fs/driver/fs_findmtddriver.c \
	third_party/nuttx/fs/driver/fs_mtdproxy.c \
	third_party/nuttx/fs/driver/fs_openblockdriver.c \
	third_party/nuttx/fs/driver/fs_registerblockdriver.c \
	third_party/nuttx/fs/driver/fs_registerdriver.c \
	third_party/nuttx/fs/driver/fs_registermtddriver.c \
	third_party/nuttx/fs/driver/fs_unregisterblockdriver.c \
	third_party/nuttx/fs/driver/fs_unregisterdriver.c \
	third_party/nuttx/fs/driver/fs_unregistermtddriver.c \
	third_party/nuttx/fs/fs_initialize.c \
	third_party/nuttx/fs/inode/fs_files.c \
	third_party/nuttx/fs/inode/fs_foreachinode.c \
	third_party/nuttx/fs/inode/fs_inode.c \
	third_party/nuttx/fs/inode/fs_inodeaddref.c \
	third_party/nuttx/fs/inode/fs_inodefind.c \
	third_party/nuttx/fs/inode/fs_inodefree.c \
	third_party/nuttx/fs/inode/fs_inoderelease.c \
	third_party/nuttx/fs/inode/fs_inoderemove.c \
	third_party/nuttx/fs/inode/fs_inodereserve.c \
	third_party/nuttx/fs/inode/fs_inodesearch.c \
	third_party/nuttx/fs/mmap/fs_mmap.c \
	third_party/nuttx/fs/mmap/fs_munmap.c \
	third_party/nuttx/fs/mount/fs_foreachmountpoint.c \
	third_party/nuttx/fs/mount/fs_mount.c \
	third_party/nuttx/fs/mount/fs_umount.c \
	third_party/nuttx/fs/partition/fs_gpt.c \
	third_party/nuttx/fs/partition/fs_partition.c \
	third_party/nuttx/fs/romfs/fs_romfs.c \
	third_party/nuttx/fs/romfs/fs_romfsutil.c \
	third_party/nuttx/fs/vfs/fs_close.c \
	third_party/nuttx/fs/vfs/fs_dup.c \
	third_party/nuttx/fs/vfs/fs_dup2.c \
	third_party/nuttx/fs/vfs/fs_epoll.c \
	third_party/nuttx/fs/vfs/fs_fcntl.c \
	third_party/nuttx/fs/vfs/fs_fstat.c \
	third_party/nuttx/fs/vfs/fs_fsync.c \
	third_party/nuttx/fs/vfs/fs_ioctl.c \
	third_party/nuttx/fs/vfs/fs_lseek.c \
	third_party/nuttx/fs/vfs/fs_mkdir.c \
	third_party/nuttx/fs/vfs/fs_open.c \
	third_party/nuttx/fs/vfs/fs_poll.c \
	third_party/nuttx/fs/vfs/fs_pread.c \
	third_party/nuttx/fs/vfs/fs_pwrite.c \
	third_party/nuttx/fs/vfs/fs_read.c \
	third_party/nuttx/fs/vfs/fs_rename.c \
	third_party/nuttx/fs/vfs/fs_rmdir.c \
	third_party/nuttx/fs/vfs/fs_select.c \
	third_party/nuttx/fs/vfs/fs_sendfile.c \
	third_party/nuttx/fs/vfs/fs_stat.c \
	third_party/nuttx/fs/vfs/fs_statfs.c \
	third_party/nuttx/fs/vfs/fs_truncate.c \
	third_party/nuttx/fs/vfs/fs_unlink.c \
	third_party/nuttx/fs/vfs/fs_write.c \
	third_party/nuttx/libs/libc/libgen/lib_dirname.c \
	third_party/nuttx/libs/libc/misc/lib_fnmatch.c \
	third_party/nuttx/libs/libc/queue/dq_addlast.c \
	third_party/nuttx/libs/libc/queue/dq_rem.c \
	third_party/nuttx/libs/libc/queue/dq_remfirst.c \
	third_party/nuttx/libs/libc/unistd/lib_access.c \
	third_party/nuttx/libs/libc/unistd/lib_chdir.c \
	third_party/nuttx/libs/libc/unistd/lib_getcwd.c \
	third_party/nuttx/libs/libc/unistd/lib_pipe.c \
	third_party/nuttx/libs/libc/unistd/lib_pipe2.c \
	third_party/nuttx/sched/wqueue/kwork_cancel.c \
	third_party/nuttx/sched/wqueue/kwork_hpthread.c \
	third_party/nuttx/sched/wqueue/kwork_lpthread.c \
	third_party/nuttx/sched/wqueue/kwork_notifier.c \
	third_party/nuttx/sched/wqueue/kwork_process.c \
	third_party/nuttx/sched/wqueue/kwork_queue.c \
